# Site Information

name: Digital Humanities Research Institute at Southern Methodist University
description: Digital Humanities Research Institute at Southern Methodist University
url: https://dhrismu.github.io/home/
title: Digital Humanities Research Institute at SMU
host-institution: Fondren Library, SMU
host-institution-url: https://www.smu.edu/
date-range: August 19-24, 2019
apply-link: https://smu.az1.qualtrics.com/jfe/form/SV_43dMdz0s9s4B1J3
author: 
  name: DHRI@SMU
  email: rmirza@smu.edu
  url: https://www.smu.edu/Libraries
  twitter: smu_libraries 
  github: https://github.com/DHRISMU
  address: Fondren Library <br>6414 Robert S. Hyer Lane <br>Dallas, TX 75205 </br>
  description: DHRI at SMU is a pilot program that is working towards building and sustaining an active community around the shared idea of Digital Humanities and Digital Scholarship. 

# A list of courses that appears on the curriculum page
# Note that link-reference should be one short, descriptive word
courses:
  - name: Welcome
    url: https://github.com/DHRISMU/intro 
    link-reference: intro
    description: pre attendance information. Additional description forthcoming. 
  - name: Digital Humanities
    url: https://github.com/DHRISMU/dh
    link-reference: dh
    description: Intro to DH jargon and terminology, attendees will learn to define DH in a way that is useful for them.
  - name: Coding
    url: https://github.com/DHRISMU/code 
    link-reference: code 
    description: What do we mean by coding? 
  - name: Command Line
    url: https://github.com/DHRISMU/command-line 
    link-reference: terminal
    description: Introduction to the UNIX command line. Topics covered will include navigating the filesystem, manipulating the environment, executing useful commands, and using pipes to communicate between programs. This session will teach you how to communicate directly with your computer’s operating system using a text-based interface and is a useful first step in learning many other technical skills.
  - name: Git
    url: https://github.com/DHRISMU/git 
    link-reference: git
    description: Git is a tool for managing changes to a set of files. It allows users to access open source repositories, recover earlier versions of a project, and collaborate with other contributors. This session will be beneficial to anyone working with data, code, or text.
  - name: R
    url: https://github.com/DHRISMU/r
    link-reference:  r
    description: R is a programming language that can be used for a wide range of tasks, including collecting and analyzing data in a variety of formats. Additional description forthcoming. 
  - name: Data
    url: https://github.com/DHRISMU/data 
    link-reference: data
    description: What is data? Additional description forthcoming. 
  - name: Geospatial Data
    url: https://github.com/DHRISMU/geospatialdata 
    link-reference: geospatial
    description: This session will introduce geospatial data and analysis. Additional description forthcoming. 
 # - name: Digital Ethics
 #   url: https://github.com/DHRI-Curriculum/ethics
 #   link-reference: ethics
 #   description: A discussion of digital ethics with an emphasis on social justice, transparency, and accessibility.

# this tells Jekyll to build the site in the "docs"
# directory, which is ideal for hosting by GitHub Pages
destination: docs


# Files that won't be included in the compiled version of the site
exclude:
  - '*.sh'
  - CNAME
  - bower_components
  - node_modules
  - _images
  - '.*'
  - 'gulpfile.js'
  - 'build_vendor.js'
  - 'get_data.js'
  - 'README.md'

# _config.stage.yml overwrites these options when you run locally
future: false
limit_posts: 10 # Only make the last 10 posts so generating isn't slow
show_drafts: false

#required by github-pages
lsi: false # Disables the more accurate related posts
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
